In [1]:
import numpy as np

In [2]:
arr1=[1,2,3,4]
arr1

[1, 2, 3, 4]

In [4]:
n1=np.array(arr1)
n1



array([1, 2, 3, 4])

In [6]:
type(n1)

numpy.ndarray

In [33]:
n2=np.array([[1,0,0],[0,1,0],[0,0,1]])
n2.itemsize
n2.dtype

dtype('int64')

In [12]:
n3=np.zeros((5,2))
n3

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n3=np.ones((5,5))
n3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
n4=np.linspace(1,10,20)
n4


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [23]:
n5=np.arange(1,5)
n5

array([1, 2, 3, 4])

In [24]:
n2.shape

(3, 3)

In [31]:
n6=np.array([[[1,0],[0,1],[1,0]],[[1,0],[0,1],[1,0]]])
n6
n6.shape
n6.ndim
n6.size
n6.itemsize

8

In [44]:
arr12=np.arange(24).reshape(6,4)

arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
arr12[2]
arr12[4:5,2:3]


array([[18]])

In [63]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [66]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [67]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9,])

In [68]:
arr2-arr1

array([3, 3, 3, 3, 3, 3])

In [70]:
arr1*12

array([12, 24, 36, 48, 60, 72])

In [71]:
arr1>4

array([False, False, False, False,  True,  True])